networks:
  wildlens-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.33-oracle
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wildlens
      MYSQL_DATABASE_EXTRA: grafana_db
      MYSQL_USER: grafana
      MYSQL_PASSWORD: grafana
    ports:
      - "3306:3306"
    networks:
      - wildlens-network
    volumes:
      - ./installation/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  grafana_pg:
    image: grafana/grafana:latest
    container_name: grafana_pg
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=mysql
      - GF_DATABASE_NAME=grafana_db
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=grafana
      - GF_LOG_LEVEL=warn

    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wildlens-network

  backend:
    image: cedsanc/backend-wildlens:1.3.6
    container_name: backend-wildlens
    ports:
      - "5001:5001"
    env_file:
      - .env
#    volumes:
#      - ${IMAGES_DIR}:/app/Backend/static/images
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wildlens-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  grafana-storage:
