networks:
  wildlens-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.33-oracle
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wildlens
      MYSQL_DATABASE_EXTRA: grafana_db
      MYSQL_USER: grafana
      MYSQL_PASSWORD: grafana
    ports:
      - "3306:3306"
    networks:
      - wildlens-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./installation/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  backend:
    image: cedsanc/backend-wildlens:latest
    container_name: backend-wildlens
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ${IMAGES_DIR_HOST}:${IMAGES_DIR_CONTAINER}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wildlens-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:
