networks:
  wildlens-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.33-oracle
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wildlens
      MYSQL_USER: grafana
      MYSQL_PASSWORD: grafana
    ports:
      - "3306:3306"
    networks:
      - wildlens-network
    volumes:
      - ./installation/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  python-env:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-data-env
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./data:/app/data
    networks:
      - wildlens-network

  grafana_pg:
    image: grafana/grafana:latest
    container_name: grafana_pg
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=mysql
      - GF_DATABASE_NAME=grafana_db
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=grafana
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wildlens-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wildlens-network

volumes:
  grafana-storage:
