networks:
  wildlens-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.33-oracle
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wildlens
    ports:
      - "3306:3306"
    networks:
      - wildlens-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  python-env:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-data-env
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./data:/app/data
    networks:
      - wildlens-network

  grafana_pg:
    image: grafana/grafana:latest
    container_name: grafana_pg
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - grafana-storage-pg:/var/lib/grafana
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgresql
      - GF_DATABASE_NAME=wildlens
      - GF_DATABASE_USER=root
      - GF_DATABASE_PASSWORD=root
    depends_on:
      - postgresql
