{
 "title": "Wildlens dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Espèces avec leur Coefficient de Multiplication et Nombre d'Images",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "grafana_db",
     "rawSql": "SELECT f.nom_fr AS espece, \n       f.coeff_multiplication, \n       COUNT(i.id_image) AS nombre_images\nFROM wildlens_facts f\nLEFT JOIN wildlens_images i ON f.id_espece = i.id_espece\nGROUP BY f.nom_fr, f.coeff_multiplication\nORDER BY f.coeff_multiplication DESC;\n"
    }
   ]
  },
  {
   "title": "Diversité des états - par animal",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "grafana_db",
     "rawSql": "SELECT f.nom_fr AS espece, e.type AS etat, COUNT(i.id_image) AS nombre_images\nFROM wildlens_images i\nJOIN wildlens_facts f ON i.id_espece = f.id_espece\nJOIN wildlens_etat e ON i.id_etat = e.id_etat\nGROUP BY f.nom_fr, e.type\nORDER BY f.nom_fr ASC, nombre_images DESC;\n"
    }
   ]
  },
  {
   "title": "Comparaison train / val / test",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "grafana_db",
     "rawSql": "SELECT e.type, COUNT(i.id_image) AS nombre_images\nFROM wildlens_etat e\nLEFT JOIN wildlens_images i ON e.id_etat = i.id_etat\nGROUP BY e.type\nORDER BY nombre_images DESC;\n"
    }
   ]
  },
  {
   "title": "Nombre d'image par espèce",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "grafana_db",
     "rawSql": "SELECT f.nom_fr AS espece, COUNT(i.id_image) AS nombre_images\nFROM wildlens_facts f\nLEFT JOIN wildlens_images i ON f.id_espece = i.id_espece\nGROUP BY f.nom_fr\nORDER BY nombre_images DESC;\n"
    }
   ]
  },
  {
   "title": "Nombre total d'image",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "wildlens",
     "rawSql": "SELECT COUNT(*) AS total_images FROM wildlens_images;\n"
    }
   ]
  }
 ]
}